version: "3"
services:
    db:
        container_name: mongoDB
        image: mongo:latest
        restart: always
        volumes:
            - ~/Syxbot-API:/data/db
        ports:
            - 27017:27017
    app:
        container_name: Syxbot-API
        restart: always
        links:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9000:9000