version: "3"
services:
    mongo:
        image: mongo:latest
        restart: always
        volumes:
            - dbdata:/data/db
        ports:
            - 27017:27017
        command: --quiet
    app:
        container_name: 'syxbot-api'
        depends_on:
            - mongo
        links:
            - mongo
        restart: always
        environment: 
            APP_DB_HOST: mongo
        build: .
        ports:
            - 9000:9000

volumes:
    dbdata: